baseurl = "/"
DefaultContentLanguage = "fr"
languageCode = "fr-fr"
title = "Python pour un data scientist/economist"
theme="hugo-theme-techdoc"
enableGitInfo = true
enableEmoji = true

disableToc = true


# Global menu section
# See https://gohugo.io/content-management/menus/
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Github"
        url = "https://github.com/linogaliana/python-datascientist"
weight = 2